config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :aires
  root 'aires#index'

end

app/models/aire.rb
class Aire < ActiveRecord::Base
  belongs_to :user
  belongs_to :marca

  has_attached_file :aire_img, :styles => { :aire_index => "250x350>", :aire_show "325x475>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :aire_img, content_type: /\Aimage\/.*\Z/
end

app/models/marca.rb
class Marca < ActiveRecord::Base
  has_many :aires
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :aires
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/aires_controller.rb
class AiresController < ApplicationController
  before_action :find_aire, only: [:show, :edit, :update, :destroy]

  def index
    if params[:marca].blank?
    @aires = Aire.all.order("created_at DESC")
  else
    @marca_id = Marca.find_by(nombre: params[:marca]).id
    @aires = Aire.where(:marca_id => @marca_id).order("created_at DESC")
  end
  end

  def show
  end

  def new
    @aire = current_user.aires.build
    @marcas = Marca.all.map { |m| [m.nombre, m.id]  }
  end

  def create
    @aire = current_user.aires.build(aire_params)
    @aire.marca_id = params[:marca_id]
    if @aire.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def edit
    @marcas = Marca.all.map { |m| [m.nombre, m.id]  }
  end

  def update
    @aire.marca_id = params[:marca_id]

    if @aire.update(aire_params)
      redirect_to aire_path(@aire)
    else
      render 'edit'
    end
  end

  def destroy
    @aire.destroy
    redirect_to root_path
  end


  private

  def aire_params
    params.require(:aire).permit(:marca_id, :modelo_conjunto, :modelo_ui, :modelo_ue, :aire_img)
  end

  def find_aire
    @aire = Aire.find(params[:id])
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/aires_helper.rb
module AiresHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/aires/_form.html.erb
<%= simple_form_for @aire do |f| %>
<%= f.input :modelo_conjunto, label: "Modelo del Conjunto" %>
<%= f.input :modelo_ui, label: "Modelo Unidad Interior" %>
<%= f.input :modelo_ue, label: "Modelo Unidad Exterior" %>
<%= f.button :submit %>
<% end %>

app/views/aires/edit.html.erb
<h1>Editar Ficha</h1>
<%= simple_form_for @aire, html: {multipart: true} do |f| %>
<%= f.file_field :aire_img %>
<%= f.select :marca_id, @marcas %>
<%= f.input :modelo_conjunto, label: "Modelo del Conjunto" %>
<%= f.input :modelo_ui, label: "Modelo Unidad Interior" %>
<%= f.input :modelo_ue, label: "Modelo Unidad Exterior" %>
<%= f.button :submit %>
<% end %>

app/views/aires/index.html.erb
<h1 class="current-marca"><%= params[:marca] %></h1>
<% if @aires.count == 0 %>
  <h3>No existen aires de esta marca</h3>
<% else %>
  <% @aires.each do |aire| %>
    <h2><%= link_to aire.modelo_conjunto, aire_path(aire) %></h2>
    <% end %>
<% end %>

app/views/aires/new.html.erb
<h1>Nueva Ficha</h1>
<%= simple_form_for @aire do |f| %>
<%= select_tag(:marca_id, options_for_select(@marcas), :prompt => "Seleccione una Marca") %>
<%= f.file_field :aire_img %>
<%= f.input :modelo_conjunto, label: "Modelo del Conjunto" %>
<%= f.input :modelo_ui, label: "Modelo Unidad Interior" %>
<%= f.input :modelo_ue, label: "Modelo Unidad Exterior" %>
<%= f.button :submit %>
<% end %>

app/views/aires/show.html.erb
<h3><%= @aire.modelo_conjunto %></h3>
<h4><%= @aire.modelo_ui %></h4>
<h4><%= @aire.modelo_ue %></h4>

<div class="links btn-group">
    <% if user_signed_in? %>
    <% if @aire.user_id == current_user.id %>
    <%= link_to "Editar", edit_aire_path(@aire) %>
    <%= link_to "Delete", aire_path(@aire), method: :delete, data: {confirm: "¿Estás seguro?"} %>
    <% end %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Airebase</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
        <%= csrf_meta_tags %>

    </head>
    <body>
        <nav class="navbar navbar-default">
            <div class="container">
                <div class="navbar-header">
                    <%= link_to "Airebase", root_path, class: "navbar-brand" %>
                </div>
                <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                    <li><%= link_to "Salir", destroy_user_session_path, method: :delete %></li>
                <% else %>
                    <li><%= link_to "Registrarse", new_user_registration_path %></li>
                    <li><%= link_to "Entrar", new_user_session_path  %></li>
                    <% end %>
                </ul>
                <ul class="nav navbar-nav">
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            Marcas
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <% Marca.all.each do |marca| %>
                            <li class="<%= 'active' if params[:marca] == marca.nombre %>">
                                <%= link_to marca.nombre, aires_path(marca: marca.nombre), class: "link" %>
                            </li>
                            <% end %>
                        </ul>
                    </li>
                    <% if user_signed_in? %>
                    <li><%= link_to "Añadir Ficha", new_aire_path %></li>
                    <% end %>
                </ul>

            </div>

        </nav>

        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
        <div class="container">
            <%= yield %>
        </div>

    </body>
</html>